// /lib/casinoData.ts

export const casinoData = [
    {
      id: "wonder",
      name: "ワンダーカジノ",
      logo: "/wondercasino_logo.png",
      banner: "/wondercasino_logo.png",
      bonus: "登録ボーナス$30！初回入金100%ボーナス（最大$500）",
      rating: 4.8,
      description: "初心者にも優しい充実のサポートと、幅広いゲームラインナップが魅力のワンダーカジノ。登録ボーナスでお得に始めよう！",
      officialLink: "https://tracker-pm2.casino-wonder.com/link?btag=96420424_437635",
    },
    {
      id: "duelbits",
      name: "デュエルビッツ",
      logo: "/duelbits_logo.png",
      banner: "/duelbits_logo.png",
      bonus: "最大$1000のウェルカムパッケージ",
      rating: 4.7,
      description: "仮想通貨に特化した次世代カジノ。独自のオリジナルゲームと充実したVIP特典が魅力！",
      officialLink: "https://affiliates.duelbits.com/visit/?bta=35925&nci=5768",
    },
    {
      id: "k8",
      name: "K8カジノ",
      logo: "/k8_logo.png",
      banner: "/k8_logo.png",
      bonus: "初回入金100%ボーナス（最大$800）＋288回のフリースピン",
      rating: 4.7,
      description: "豊富なスロットと旧式パチスロも楽しめる高額ボーナス付きカジノ。",
      officialLink: "https://k8.io/?invite=calron",
    },
    {
      id: "parimatch",
      name: "パリマッチカジノ",
      logo: "/parimatch_logo.png",
      banner: "/parimatch_logo.png",
      bonus: "初回入金150%ボーナス（最大$1,500）",
      rating: 4.6,
      description: "スポーツベットに強みを持つ世界的ブックメーカー兼カジノ。",
      officialLink: "https://affcl.org/?serial=61314390&creative_id=4261",
    },
    {
      id: "stake",
      name: "Stakeカジノ",
      logo: "/stake_logo.png",
      banner: "/stake_logo.png",
      bonus: "初回入金200%ボーナス（最大$2,000）＋入金不要ボーナス$14",
      rating: 4.8,
      description: "仮想通貨専門の高還元カジノ。VIP待遇が魅力！",
      officialLink: "https://stake.com/?c=aLjELsQU&offer=calro200",
    },
    {
      id: "kachiwin",
      name: "勝win",
      logo: "/katsu.jpg",
      banner: "/katsu.jpg",
      bonus: "最大$1000のウェルカムボーナス",
      rating: 4.5,
      description: "スポーツもカジノも楽しめる、日本特化型の総合サイト。",
      officialLink: "https://tracker.katsuwinaffiliates.ai/link?btag=90306436_414265",
    },
  ]
  